"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { AnimatePresence, motion, useScroll, useSpring, useTransform } from "framer-motion";
import { ArrowDownRight, ArrowLeft, ArrowRight, ArrowUpRight, Braces, Check, ChevronRight, Code2, Command, Mail, Menu, Search, Send, Sparkles, X } from "lucide-react";
import projectsData from "../data/projects.json";

type Project = (typeof projectsData)[number];
type View = "home" | "projects" | "about" | "contact";
const Github = Code2;
const Linkedin = ArrowUpRight;
const nav: { label: string; href: string; view: View }[] = [
  { label: "Home", href: "/", view: "home" }, { label: "Projects", href: "/projects", view: "projects" },
  { label: "About", href: "/about", view: "about" }, { label: "Contact", href: "/contact", view: "contact" },
];
const ease = [0.22, 1, 0.36, 1] as const;

function Loader() {
  const [show, setShow] = useState(true);
  useEffect(() => { const id = setTimeout(() => setShow(false), 950); return () => clearTimeout(id); }, []);
  return <AnimatePresence>{show && <motion.div className="loader" exit={{ opacity: 0 }} transition={{ duration: .45 }}><motion.div initial={{ y: 20, opacity: 0 }} animate={{ y: 0, opacity: 1 }} className="loader-mark">a<span>.</span></motion.div><div className="loader-line"><motion.i initial={{ scaleX: 0 }} animate={{ scaleX: 1 }} transition={{ duration: .7, ease }} /></div></motion.div>}</AnimatePresence>;
}

function Shell({ active, children }: { active?: View; children: React.ReactNode }) {
  const [menu, setMenu] = useState(false), [palette, setPalette] = useState(false);
  const { scrollYProgress } = useScroll(); const progress = useSpring(scrollYProgress, { stiffness: 130, damping: 28 });
  useEffect(() => { const key = (e: KeyboardEvent) => { if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === "k") { e.preventDefault(); setPalette(v => !v); } if (e.key === "Escape") { setPalette(false); setMenu(false); } }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, []);
  return <><Loader/><motion.div className="scroll-progress" style={{ scaleX: progress }} /><div className="ambient"><i/><i/><i/></div><header><Link href="/" className="brand">anami<span>.dev</span></Link><nav>{nav.map(n => <Link key={n.view} className={active === n.view ? "active" : ""} href={n.href}>{n.label}</Link>)}</nav><button className="command" onClick={() => setPalette(true)} aria-label="Open command palette"><Command size={14}/><span>⌘ K</span></button><button className="menu-btn" onClick={() => setMenu(true)} aria-label="Open menu"><Menu/></button></header>
  <main>{children}</main><footer><div><Link href="/" className="brand">anami<span>.dev</span></Link><p>Designed & built with unreasonable care.</p></div><div className="footer-links"><a href="#">GitHub ↗</a><a href="#">LinkedIn ↗</a><a href="mailto:hello@anami.dev">Email ↗</a></div><small>© 2026 Anamika</small></footer>
  <AnimatePresence>{menu && <motion.div className="mobile-menu" initial={{ opacity:0 }} animate={{ opacity:1 }} exit={{ opacity:0 }}><button onClick={() => setMenu(false)}><X/></button>{nav.map(n=><Link key={n.view} href={n.href}>{n.label}<ArrowUpRight/></Link>)}</motion.div>}</AnimatePresence>
  <AnimatePresence>{palette && <motion.div className="palette-wrap" initial={{ opacity:0 }} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={() => setPalette(false)}><motion.div className="palette" initial={{ y:-20, scale:.97 }} animate={{y:0,scale:1}} onMouseDown={e=>e.stopPropagation()}><div className="palette-search"><Search/><input autoFocus placeholder="Where do you want to go?" /></div><span className="palette-label">NAVIGATE</span>{nav.map(n=><Link key={n.view} href={n.href}><span>{n.view === "home" ? <Sparkles/> : n.view === "projects" ? <Braces/> : n.view === "contact" ? <Mail/> : <Code2/>}{n.label}</span><span>↵</span></Link>)}</motion.div></motion.div>}</AnimatePresence>
  </>;
}

function Reveal({ children, className = "", delay=0 }: { children: React.ReactNode; className?: string; delay?: number }) { return <motion.div className={className} initial={{ opacity:0, y:36, filter:"blur(10px)" }} whileInView={{opacity:1,y:0,filter:"blur(0px)"}} viewport={{once:true,margin:"-60px"}} transition={{duration:.75,delay,ease}}>{children}</motion.div>; }

function ProjectVisual({ project, compact=false }: { project: Project; compact?: boolean }) { return <div className={`project-visual ${compact?"compact":""}`} style={{"--accent": project.accent} as React.CSSProperties}><div className="visual-glow"/><div className="fake-window"><div className="window-bar"><i/><i/><i/><span>{project.name.toLowerCase()}.app</span></div><div className="window-body"><div className="app-sidebar"><b>{project.name.charAt(0)}</b><i/><i/><i/></div><div className="app-content"><span className="tiny-label">TODAY’S FOCUS</span><h4>{project.tagline.split(".")[0]}</h4><div className="data-row"><div><i/><i/></div><strong>{project.metric}</strong></div><div className="mini-grid"><i/><i/><i/></div></div></div></div></div>; }

function ProjectCard({ project, featured=false }: { project: Project; featured?: boolean }) { return <motion.article className={`project-card ${featured?"featured":""}`} whileHover={{y:-8}} transition={{type:"spring",stiffness:250,damping:20}}><ProjectVisual project={project} compact={!featured}/><div className="project-copy"><div className="project-meta"><span>{project.index} / {project.category}</span><span>{project.year}</span></div><h3>{project.name}</h3><p>{project.description}</p><div className="tags">{project.stack.slice(0,3).map(t=><span key={t}>{t}</span>)}</div><Link href={`/projects/${project.slug}`} className="text-link">Explore project <ArrowUpRight/></Link></div></motion.article>; }

function Home() {
  const roles=["apps.","AI.","experiments."]; const [role,setRole]=useState(0);
  useEffect(()=>{const id=setInterval(()=>setRole(r=>(r+1)%roles.length),1800);return()=>clearInterval(id)},[]);
  const {scrollY}=useScroll(); const heroY=useTransform(scrollY,[0,700],[0,150]);
  return <Shell active="home"><section className="hero"><motion.div className="hero-grid" style={{y:heroY}}/><div className="hero-kicker"><span className="status-dot"/> Student builder · Available for interesting ideas</div><motion.h1 initial={{opacity:0,y:50}} animate={{opacity:1,y:0}} transition={{duration:.9,ease}}>I make ideas<br/><span>feel</span> real.</motion.h1><div className="hero-bottom"><p>Hi, I’m <b>Anamika</b> — an AI developer and student builder crafting thoughtful digital products at the edge of <AnimatePresence mode="wait"><motion.em key={role} initial={{y:12,opacity:0}} animate={{y:0,opacity:1}} exit={{y:-12,opacity:0}}>{roles[role]}</motion.em></AnimatePresence></p><Link href="/projects" className="primary-btn">Explore my apps <ArrowDownRight/></Link></div><div className="scroll-note">SCROLL TO EXPLORE <ArrowDownRight/></div></section>
  <section className="featured-section"><Reveal className="section-head"><div><span className="eyebrow">01 / SELECTED WORK</span><h2>Built to be<br/><i>used.</i></h2></div><p>Independent apps, intelligent systems, and ambitious experiments—each made with purpose.</p></Reveal><Reveal><ProjectCard project={projectsData[0]} featured/></Reveal><div className="card-pair">{projectsData.slice(1,3).map((p,i)=><Reveal key={p.slug} delay={i*.08}><ProjectCard project={p}/></Reveal>)}</div><Link href="/projects" className="all-work">View all projects <ArrowRight/></Link></section>
  <section className="numbers"><Reveal><span className="eyebrow">02 / BY THE NUMBERS</span><h2>Small team.<br/><i>Big output.</i></h2></Reveal><div className="stat-grid">{[["08+","Apps built"],["05","Hackathons"],["03","Awards"],["2.4k","Early users"],["12","Languages & tools"]].map((s,i)=><Reveal key={s[1]} delay={i*.05} className="stat"><strong>{s[0]}</strong><span>{s[1]}</span></Reveal>)}</div></section>
  <section className="cta"><Reveal><span className="eyebrow">NEXT IDEA</span><h2>Let’s build something<br/><i>people remember.</i></h2><Link href="/contact" className="primary-btn">Start a conversation <ArrowUpRight/></Link></Reveal></section></Shell>;
}

function Projects() { const cats=["All","AI","Mobile","Web","Data Science","Hackathons"]; const [cat,setCat]=useState("All"),[query,setQuery]=useState(""); const shown=useMemo(()=>projectsData.filter(p=>(cat==="All"||p.category===cat)&&p.name.toLowerCase().includes(query.toLowerCase())),[cat,query]); return <Shell active="projects"><section className="page-hero"><span className="eyebrow">THE WORK / 2024—NOW</span><h1>Ideas, <i>shipped.</i></h1><p>A growing collection of apps, intelligent systems, research, and experiments built to solve real problems.</p></section><section className="project-browser"><div className="filters"><div>{cats.map(c=><button className={cat===c?"selected":""} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search projects"/></label></div><motion.div layout className="projects-grid"><AnimatePresence mode="popLayout">{shown.map(p=><motion.div layout key={p.slug} initial={{opacity:0,scale:.94}} animate={{opacity:1,scale:1}} exit={{opacity:0,scale:.94}}><ProjectCard project={p}/></motion.div>)}</AnimatePresence></motion.div></section></Shell>; }

function About() { const journey=[["2026","Building at the edge of AI","Exploring agents, adaptive interfaces, and products that feel quietly intelligent."],["2025","First hackathon win","Built Care Canvas in 36 hours and learned that constraints are creative fuel."],["2024","The first real app","Turned a small frustration into a tool classmates actually wanted to use."],["Before","Curiosity became a habit","Took things apart, asked too many questions, and slowly learned to make ideas tangible."]]; return <Shell active="about"><section className="page-hero about-hero"><span className="eyebrow">ABOUT / THE HUMAN BIT</span><h1>Curious by nature.<br/><i>Builder by choice.</i></h1><p>I’m Anamika, a student developer who likes the difficult middle: where a promising idea becomes a product someone can actually use.</p></section><section className="story"><Reveal><p className="story-lead">I don’t just want to write code. I want to understand people, find the friction, and make technology feel <i>obvious.</i></p></Reveal><div className="story-grid"><Reveal><span className="eyebrow">WHAT DRIVES ME</span><p>I’m happiest moving between product thinking, visual design, and engineering. That mix is where useful things become memorable ones.</p></Reveal><Reveal><span className="eyebrow">CURRENTLY EXPLORING</span><p>Human-centered AI, spatial interfaces, small language models, playful data tools, and the craft behind calm software.</p></Reveal></div></section><section className="journey"><Reveal><span className="eyebrow">THE JOURNEY</span><h2>Still early.<br/><i>Already moving.</i></h2></Reveal><div className="timeline">{journey.map((j,i)=><Reveal key={j[0]} className="timeline-row"><span>{j[0]}</span><div><h3>{j[1]}</h3><p>{j[2]}</p></div><b>0{i+1}</b></Reveal>)}</div></section><section className="skills"><Reveal><span className="eyebrow">TOOLS I REACH FOR</span></Reveal><div>{["TypeScript","Python","React","Next.js","React Native","OpenAI","Supabase","Postgres","Figma","Framer Motion"].map(s=><span key={s}>{s}</span>)}</div></section></Shell>; }

function Contact() { const [sent,setSent]=useState(false); return <Shell active="contact"><section className="contact-layout"><div><span className="eyebrow">CONTACT / SAY HELLO</span><h1>Have an idea?<br/><i>I’m listening.</i></h1><p>Whether it’s a collaboration, an internship, or just a good question—send it my way.</p><div className="socials"><a href="mailto:hello@anami.dev"><Mail/>Email<span>hello@anami.dev</span><ArrowUpRight/></a><a href="#"><Github/>GitHub<span>@anamika</span><ArrowUpRight/></a><a href="#"><Linkedin/>LinkedIn<span>/in/anamika</span><ArrowUpRight/></a></div></div><form onSubmit={e=>{e.preventDefault();setSent(true)}}><label>Your name<input required placeholder="Ada Lovelace"/></label><label>Your email<input required type="email" placeholder="ada@example.com"/></label><label>What are you thinking?<textarea required placeholder="Tell me about the idea, the problem, or just say hi..."/></label><button className="primary-btn" type="submit">{sent?<><Check/> Message ready</>:<>Send message <Send/></>}</button>{sent&&<p className="form-note">Thanks! This demo form is ready to connect to your email service.</p>}</form></section></Shell>; }

export function Portfolio({view}: {view: View}) { return view === "projects" ? <Projects/> : view === "about" ? <About/> : view === "contact" ? <Contact/> : <Home/>; }

export function ProjectDetail({project}: {project: Project}) { return <Shell><section className="detail-hero" style={{"--accent":project.accent} as React.CSSProperties}><Link href="/projects" className="back"><ArrowLeft/> All projects</Link><div className="detail-title"><span className="eyebrow">{project.category} / {project.year}</span><h1>{project.name}</h1><p>{project.tagline}</p><div><a className="primary-btn" href="#">Live demo <ArrowUpRight/></a><a className="secondary-btn" href="#"><Github/> GitHub</a></div></div><ProjectVisual project={project}/></section><section className="detail-body"><Reveal className="overview"><span className="eyebrow">OVERVIEW</span><p>{project.description} The result is a focused product that makes a complex task feel immediate, clear, and surprisingly human.</p><div className="detail-meta"><span><small>STATUS</small>{project.status}</span><span><small>YEAR</small>{project.year}</span><span><small>IMPACT</small>{project.metric}</span></div></Reveal><div className="case-grid"><Reveal><span className="eyebrow">01 / THE PROBLEM</span><h2>Complexity was getting in the way.</h2><p>Existing tools asked people to adapt to the system. Important context was fragmented, workflows were slow, and the experience created more cognitive load than clarity.</p></Reveal><Reveal><span className="eyebrow">02 / THE SOLUTION</span><h2>A calmer, smarter path forward.</h2><p>{project.name} brings the essential signals into one thoughtful flow—using automation where it helps and staying out of the way where it doesn’t.</p></Reveal></div><Reveal className="feature-block"><span className="eyebrow">03 / CORE FEATURES</span><div>{project.features.map((f,i)=><article key={f}><span>0{i+1}</span><h3>{f}</h3><p>Designed around speed, clarity, and a small moment of delight.</p></article>)}</div></Reveal><Reveal className="architecture"><span className="eyebrow">04 / THE SYSTEM</span><h2>Simple on the surface.<br/><i>Considered underneath.</i></h2><div className="arch-flow">{project.stack.map((s,i)=><div key={s}><Code2/><span>{s}</span>{i<project.stack.length-1&&<ChevronRight/>}</div>)}</div></Reveal><div className="next-project"><span>NEXT PROJECT</span><Link href={`/projects/${projectsData[(projectsData.findIndex(p=>p.slug===project.slug)+1)%projectsData.length].slug}`}>{projectsData[(projectsData.findIndex(p=>p.slug===project.slug)+1)%projectsData.length].name}<ArrowRight/></Link></div></section></Shell>; }
