"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { AnimatePresence, motion, useScroll, useSpring } from "framer-motion";
import { ArrowDownRight, ArrowRight, ArrowUpRight, Braces, Code2, Command, Mail, Menu, Search, Sparkles, X } from "lucide-react";

type View = "home" | "projects" | "about" | "contact";
const nav = [{label:"Home",href:"/",view:"home"},{label:"Projects",href:"/projects",view:"projects"},{label:"About",href:"/about",view:"about"},{label:"Contact",href:"/contact",view:"contact"}] as const;
const ease=[.22,1,.36,1] as const;

function Loader(){const[show,setShow]=useState(true);useEffect(()=>{const id=setTimeout(()=>setShow(false),850);return()=>clearTimeout(id)},[]);return <AnimatePresence>{show&&<motion.div className="loader" exit={{opacity:0}}><div className="loader-mark">a<span>.</span></div><div className="loader-line"><motion.i initial={{scaleX:0}} animate={{scaleX:1}} transition={{duration:.65,ease}}/></div></motion.div>}</AnimatePresence>}
function Reveal({children,className="",delay=0}:{children:React.ReactNode;className?:string;delay?:number}){return <motion.div className={className} initial={{opacity:0,y:32,filter:"blur(9px)"}} whileInView={{opacity:1,y:0,filter:"blur(0)"}} viewport={{once:true,margin:"-60px"}} transition={{duration:.7,delay,ease}}>{children}</motion.div>}

function Shell({active,children}:{active?:View;children:React.ReactNode}){const[menu,setMenu]=useState(false),[palette,setPalette]=useState(false);const{scrollYProgress}=useScroll();const progress=useSpring(scrollYProgress,{stiffness:130,damping:28});useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==="k"){e.preventDefault();setPalette(v=>!v)}if(e.key==="Escape"){setPalette(false);setMenu(false)}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[]);return <><Loader/><motion.div className="scroll-progress" style={{scaleX:progress}}/><div className="ambient"><i/><i/><i/></div><header><Link href="/" className="brand">anami<span>.dev</span></Link><nav>{nav.map(n=><Link key={n.view} className={active===n.view?"active":""} href={n.href}>{n.label}</Link>)}</nav><button className="command" onClick={()=>setPalette(true)}><Command size={14}/>⌘ K</button><button className="menu-btn" onClick={()=>setMenu(true)} aria-label="Open menu"><Menu/></button></header><main>{children}</main><footer><div><Link href="/" className="brand">anami<span>.dev</span></Link><p>Designed & built with curiosity.</p></div><div className="footer-links"><a href="https://www.linkedin.com/in/anamikahareesh/" target="_blank">LinkedIn ↗</a><a href="mailto:anami.develop@gmail.com">Email ↗</a></div><small>© 2026 Anamika Hareesh</small></footer><AnimatePresence>{menu&&<motion.div className="mobile-menu" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><button onClick={()=>setMenu(false)}><X/></button>{nav.map(n=><Link key={n.view} href={n.href}>{n.label}<ArrowUpRight/></Link>)}</motion.div>}</AnimatePresence><AnimatePresence>{palette&&<motion.div className="palette-wrap" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={()=>setPalette(false)}><motion.div className="palette" onMouseDown={e=>e.stopPropagation()} initial={{y:-15,scale:.98}} animate={{y:0,scale:1}}><div className="palette-search"><Search/><span>Jump to a page</span></div><span className="palette-label">NAVIGATE</span>{nav.map(n=><Link key={n.view} href={n.href}><span>{n.view==="home"?<Sparkles/>:n.view==="projects"?<Braces/>:n.view==="contact"?<Mail/>:<Code2/>}{n.label}</span><span>↵</span></Link>)}</motion.div></motion.div>}</AnimatePresence></>}

function FocusCard({number,title,text,tags}:{number:string;title:string;text:string;tags:string[]}){return <motion.article className="focus-card" whileHover={{y:-7}} transition={{type:"spring",stiffness:240,damping:20}}><span>{number}</span><div className="focus-icon"><Code2/></div><h3>{title}</h3><p>{text}</p><div className="tags">{tags.map(t=><span key={t}>{t}</span>)}</div></motion.article>}

function Home(){return <Shell active="home"><section className="hero"><div className="hero-grid"/><div className="hero-kicker"><span className="status-dot"/> High school student · Builder · Explorer</div><motion.h1 initial={{opacity:0,y:45}} animate={{opacity:1,y:0}} transition={{duration:.85,ease}}>Building apps<br/><span>that matter.</span></motion.h1><div className="hero-bottom"><p>Hi, I’m <b>Anamika Hareesh</b> — a high school student using code and intelligent agents to build useful technology for learning and everyday life.</p><Link href="/about" className="primary-btn">Meet Anamika <ArrowDownRight/></Link></div><div className="scroll-note">KEEP EXPLORING <ArrowDownRight/></div></section><section className="featured-section"><Reveal className="section-head"><div><span className="eyebrow">01 / CURRENT EXPLORATIONS</span><h2>Learning by<br/><i>building.</i></h2></div><p>I’m especially interested in agentic systems and how AI can make education more personal, useful, and accessible.</p></Reveal><div className="focus-grid"><Reveal><FocusCard number="01" title="Agentic AI" text="Exploring systems that can reason, plan, use tools, and work alongside people." tags={["Agents","Python","AI"]}/></Reveal><Reveal delay={.08}><FocusCard number="02" title="AI-Powered Education" text="Designing intelligent tools that help students learn, plan, and make progress." tags={["Education","AI","Students"]}/></Reveal><Reveal delay={.16}><FocusCard number="03" title="App Development" text="Turning ideas into useful, polished apps and learning through every build." tags={["Xcode","Java","Product"]}/></Reveal></div><div className="honest-note"><span className="eyebrow">THE PROJECT ARCHIVE</span><p>Real projects will appear here as I finish and document them. No filler, no invented launches—just work I’m proud to share.</p><Link href="/projects">Visit the lab <ArrowRight/></Link></div></section><section className="numbers real-facts"><Reveal><span className="eyebrow">02 / THE FOUNDATION</span><h2>Curiosity,<br/><i>in motion.</i></h2></Reveal><div className="fact-grid"><Reveal><strong>Since elementary school</strong><span>I’ve been learning to code and turning questions into experiments.</span></Reveal><Reveal delay={.08}><strong>Python + Java</strong><span>My main programming languages, with many more tools along the way.</span></Reveal><Reveal delay={.16}><strong>Math + Physics</strong><span>The subjects that shape how I think about systems and solve problems.</span></Reveal></div></section><section className="cta"><Reveal><span className="eyebrow">THE NEXT IDEA</span><h2>Make something<br/><i>meaningful.</i></h2><Link href="/contact" className="primary-btn">Start a conversation <ArrowUpRight/></Link></Reveal></section></Shell>}

function Projects(){return <Shell active="projects"><section className="page-hero"><span className="eyebrow">THE LAB / REAL WORK</span><h1>Ideas,<br/><i>in motion.</i></h1><p>Projects I’ve actually built—shared with honest context, working demos, and what I learned along the way.</p></section><section className="vivr-listing project-listing"><Reveal><Link href="/projects/loka" className="loka-project-card"><div className="loka-card-art"><img src="/loka-cover.png" alt="Loka immersive learning world"/></div><div className="vivr-card-copy loka-card-copy"><div><span className="eyebrow">01 / IMMERSIVE AI · EDUCATION</span><span className="project-status">CURRENT PROTOTYPE</span></div><h2>LOKA</h2><p>An AI-powered learning platform that turns lessons into immersive worlds students can explore, question, and experience.</p><div className="tags"><span>Unity 6</span><span>OpenXR</span><span>Three.js</span><span>Agentic AI</span></div><span className="text-link">Enter the project <ArrowUpRight/></span></div></Link></Reveal><Reveal><Link href="/projects/vivr" className="vivr-project-card"><div className="vivr-card-art"><span>vivrAI</span><div className="vivr-orbit"><i/><i/><i/></div><small>AGENTIC SCHEDULING ASSISTANT</small></div><div className="vivr-card-copy"><div><span className="eyebrow">02 / AGENTIC AI · EDUCATION</span><span className="project-status">PRODUCT REALIZATION</span></div><h2>vivrAI</h2><p>An AI-powered scheduling assistant that organizes schedules, analyzes commitments, and generates personalized recommendations.</p><div className="tags"><span>Python</span><span>OpenAI Agents</span><span>Gradio</span><span>Google Calendar</span></div><span className="text-link">Explore project <ArrowUpRight/></span></div></Link></Reveal></section></Shell>}

function About(){return <Shell active="about"><section className="page-hero about-hero"><span className="eyebrow">ABOUT / ANAMIKA HAREESH</span><h1>Student today.<br/><i>Builder always.</i></h1><p>I’m a high school student building apps to make a difference. I started coding in elementary school, and I’ve been following my curiosity ever since.</p></section><section className="story"><Reveal><p className="story-lead">I’m drawn to technology that can <i>reason, create, and act.</i></p></Reveal><div className="story-grid"><Reveal><span className="eyebrow">HOW I BUILD</span><p>I use Python and Java, experiment with AI agents, build in Xcode, and prototype with Arduino. I care less about staying inside one tool and more about choosing what helps an idea become real.</p></Reveal><Reveal><span className="eyebrow">WHAT I’M EXPLORING</span><p>My main interests are agentic AI and AI-powered education—especially systems that can understand a student’s context, coordinate useful actions, and make learning or planning feel more personal.</p></Reveal></div></section><section className="journey"><Reveal><span className="eyebrow">MY PATH</span><h2>Started early.<br/><i>Still exploring.</i></h2></Reveal><div className="timeline"><Reveal className="timeline-row"><span>NOW</span><div><h3>Building with purpose</h3><p>Learning through ambitious app ideas, intelligent systems, and hands-on prototypes.</p></div><b>02</b></Reveal><Reveal className="timeline-row"><span>THEN</span><div><h3>Coding since elementary school</h3><p>What began as curiosity became a lasting way to think, experiment, and create.</p></div><b>01</b></Reveal></div></section><section className="skills"><Reveal><span className="eyebrow">MY TOOLBOX</span></Reveal><div>{["Python","Java","AI Agents","AI in Education","Xcode","Arduino","Computer Vision","Math","Physics"].map(s=><span key={s}>{s}</span>)}</div></section></Shell>}

function Contact(){return <Shell active="contact"><section className="contact-layout"><div><span className="eyebrow">CONTACT / SAY HELLO</span><h1>Let’s make<br/><i>a difference.</i></h1><p>Have an idea, an opportunity, or something interesting to share? I’d love to hear from you.</p><div className="socials"><a href="mailto:anami.develop@gmail.com"><Mail/>Email<span>anami.develop@gmail.com</span><ArrowUpRight/></a><a href="https://www.linkedin.com/in/anamikahareesh/" target="_blank"><ArrowUpRight/>LinkedIn<span>/in/anamikahareesh</span><ArrowUpRight/></a></div></div><div className="contact-card"><span className="eyebrow">BEST WAY TO REACH ME</span><h2>Send me an email.</h2><p>I’ll read it personally. Tell me what you’re building, learning, or wondering about.</p><a className="primary-btn" href="mailto:anami.develop@gmail.com">Write to Anamika <Mail/></a></div></section></Shell>}

export function Portfolio({view}:{view:View}){return view==="projects"?<Projects/>:view==="about"?<About/>:view==="contact"?<Contact/>:<Home/>}
